---
- hosts: master
  tasks:
  - apt: name=openntpd state=latest
  - service: name=openntpd state=started enabled=yes

- hosts: www
  tasks:
  - apt: name=apache2 state=latest
  - service: name=apache2 state=started enabled=yes
  - apache2_module: state=present name=proxy
    notify:
    - restart apache2
  - apache2_module: state=present name=proxy_http
    notify:
    - restart apache2
  - apache2_module: state=present name=include
    notify:
    - restart apache2
  - apache2_module: state=present name=negotiation
    notify:
    - restart apache2
  - apache2_module: state=present name=autoindex
    notify:
    - restart apache2
  - apache2_module: state=present name=alias
    notify:
    - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

- hosts: hack
  tasks:
  - apt: name=ack-grep state=present
  - apt: name=build-essential state=present
  - apt: name=curl state=present
  - apt: name=fail2ban state=present
  - apt: name=git-man state=present
  - apt: name=git state=present
  - apt: name=git-svn state=present
  - apt: name=gnupg2 state=present
  - apt: name=irssi state=present
  - apt: name=nodejs state=present
  - apt: name=npm state=present
  - apt: name=python-pygments state=present
  - apt: name=rsync state=present
  - apt: name=screen state=present
  - apt: name=strace state=present
  - apt: name=sudo state=present
  - apt: name=tmux state=present
  - apt: name=unzip state=present
  - apt: name=wget state=present
