---
- hosts: master
  tasks:
  - apt: name=openntpd state=latest
  - service: name=openntpd state=started enabled=yes

- hosts: www
  tasks:
  - apt: name={{item}} state=latest
    with_items:
        - apache2
        - build-essential
        - curl
        - pwgen
        - ruby-sass
  - file: path=/etc/apache2/sites-available state=directory
  - copy: src=files/modules.perl6.org/site.conf dest=/etc/apache2/sites-available/modules.perl6.org-mojo.conf owner=root mode=644
    notify: restart apache2
#  - command: a2ensite modules.perl6.org.org-mojo.conf
#    notify: restart apache2
  - service: name=apache2 state=started enabled=yes
  - apache2_module: state=present name={{ item }}
    notify:
    - restart apache2
    with_items:
        - proxy
        - proxy_http
        - include
        - negotiation
        - autoindex
        - alias

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

- hosts: hack
  tasks:
  - apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    name: Install debian packages
    with_items:
        - build-essential
        - cabal-install
        - curl
        - fail2ban
        - git-man
        - git
        - git-svn
        - gnupg2
        - irssi
        - nodejs
        - python-pygments
        - rsync
        - screen
        - strace
        - sudo
        - tmux
        - unzip
        - wget
